try to use github actions

diff --git a/.github/workflows/pr-build.yaml b/.github/workflows/pr-build.yaml
--- a/.github/workflows/pr-build.yaml
+++ b/.github/workflows/pr-build.yaml
@@ -10,47 +10,47 @@ on:
       - main
 
 jobs:
-  build-windows:
-    runs-on: windows-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: set up python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.13'
-          architecture: 'x64'
-
-      - name: install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-          pip install lxml
-          pip install pyinstaller
-
-      - name: clean previous builds
-        run: |
-          rmdir build -r -force -ErrorAction SilentlyContinue || true
-          rmdir dist -r -force -ErrorAction SilentlyContinue || true
-
-      - name: build with pyinstaller (windows)
-        run: pyinstaller meikipop.win.x64.spec
-
-      - name: build dictionary
-        run: python -m scripts.build_dictionary
-
-      - name: build windows archive
-        run: |
-          mkdir dist/meikipop
-          mv jmdict_enhanced.pkl dist/meikipop/
-          mv dist/meikipop.exe dist/meikipop/
-          powershell -Command "Compress-Archive -Path dist/meikipop -DestinationPath dist/meikipop.x64.zip"
-
-      - name: upload windows artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: meikipop-windows-x64-pr
-          path: dist/meikipop.x64.zip
+  #  build-windows:
+  #    runs-on: windows-latest
+  #    steps:
+  #      - uses: actions/checkout@v4
+  #
+  #      - name: set up python
+  #        uses: actions/setup-python@v5
+  #        with:
+  #          python-version: '3.13'
+  #          architecture: 'x64'
+  #
+  #      - name: install dependencies
+  #        run: |
+  #          python -m pip install --upgrade pip
+  #          pip install -r requirements.txt
+  #          pip install lxml
+  #          pip install pyinstaller
+  #
+  #      - name: clean previous builds
+  #        run: |
+  #          rmdir build -r -force -ErrorAction SilentlyContinue || true
+  #          rmdir dist -r -force -ErrorAction SilentlyContinue || true
+  #
+  #      - name: build with pyinstaller (windows)
+  #        run: pyinstaller meikipop.win.x64.spec
+  #
+  #      - name: build dictionary
+  #        run: python -m scripts.build_dictionary
+  #
+  #      - name: build windows archive
+  #        run: |
+  #          mkdir dist/meikipop
+  #          mv jmdict_enhanced.pkl dist/meikipop/
+  #          mv dist/meikipop.exe dist/meikipop/
+  #          powershell -Command "Compress-Archive -Path dist/meikipop -DestinationPath dist/meikipop.x64.zip"
+  #
+  #      - name: upload windows artifact
+  #        uses: actions/upload-artifact@v4
+  #        with:
+  #          name: meikipop-windows-x64-pr
+  #          path: dist/meikipop.x64.zip
 
   build-linux:
     runs-on: ubuntu-latest
@@ -64,7 +64,7 @@ jobs:
           apt-get install -y sudo
           apt-get install -y software-properties-common
           add-apt-repository ppa:deadsnakes/ppa
-          apt-get install -y python3.12 python3-pip python3.12-venv python3-distutils
+          apt-get install -y python3.12 python3-pip python3.12-venv python3-distutils python3-setuptools
 
       - name: Install Linux (Apt) dependencies
         run: |
@@ -87,7 +87,6 @@ jobs:
 
       - name: install dependencies
         run: |
-          python3.12 -m pip install setuptools
           python3.12 -m pip install --upgrade pip
           python3.12 -m pip install -r requirements.txt lxml pyinstaller
           wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
